{
    "statusCode":200,
    "status":"success",
    "message":"The process done successfully",
    "data":{
       "count":68,
       "transactions":[
          {
             "_id":"641c00d00adbc23ea4936637",
             "invoice":{
                "_id":"641c00d00adbc23ea4936625",
                "client":{
                   "email":"test@gmail.com",
                   "address":{
                      "country":"Palestine"
                   },
                   "_id":"63b5d6d66003306b9cde9048",
                   "fullName":"test test"
                },
                "currency":"USD",
                "fixed":[
                   {
                      "itemName":"prod test job",
                      "description":"test invoice",
                      "price":110,
                      "_id":"641aaaa18a6d6a280252b9a3"
                   },
                   {
                      "itemName":"prod test job",
                      "description":"test invoice",
                      "price":200,
                      "_id":"641aaaa18a6d6a280252b9a4"
                   }
                ],
                "invoiceNo":"INV-404",
                "subTotal":310,
                "freelancer":{
                   "_id":"63e104aa8bba2cb3f754d7db",
                   "firstName":"Heba",
                   "lastName":"SKHAIL"
                },
                "status":"paid"
             },
             "type":"invoice",
             "updatedAt":"2023-03-23T07:33:36.785Z"
          },
          {
             "_id":"641b828d96719d501a4bb49e",
             "invoice":{
                "_id":"641b828d96719d501a4bb497",
                "client":{
                   "_id":"6418563484d13890622696d2",
                   "email":"test@test.com",
                   "address":{
                      "country":"Palestine"
                   },
                   "fullName":"test11 test1121"
                },
                "currency":"USD",
                "fixed":[
                   {
                      "itemName":"test12",
                      "description":"tttttt",
                      "price":22,
                      "_id":"641b828d96719d501a4bb498"
                   }
                ],
                "freelancer":{
                   "_id":"63e104aa8bba2cb3f754d7db",
                   "firstName":"Heba",
                   "lastName":"SKHAIL"
                },
                "subTotal":22,
                "invoiceNo":"INV403",
                "status":"pending_approval"
             },
             "type":"invoice",
             "updatedAt":"2023-03-22T22:34:53.513Z"
          },
          {
             "_id":"641b81f296719d501a4bb436",
             "invoice":{
                "_id":"641b81f296719d501a4bb42e",
                "client":{
                   "_id":"641b81f296719d501a4bb42a",
                   "email":"Mohammed@gmail.com",
                   "address":{
                      "country":"Palestine"
                   },
                   "fullName":"taymaa"
                },
                "currency":"USD",
                "fixed":[
                   {
                      "itemName":"taymaa job",
                      "description":"test invoice",
                      "price":1000,
                      "_id":"641b81f296719d501a4bb42f"
                   },
                   {
                      "itemName":"test 2 job",
                      "description":"test invoice",
                      "price":500,
                      "_id":"641b81f296719d501a4bb430"
                   }
                ],
                "freelancer":{
                   "_id":"63e104aa8bba2cb3f754d7db",
                   "firstName":"Heba",
                   "lastName":"SKHAIL"
                },
                "subTotal":1500,
                "invoiceNo":"INV402",
                "status":"pending_approval"
             },
             "type":"invoice",
             "updatedAt":"2023-03-22T22:32:18.681Z"
          },
          {
             "_id":"641b6d4c96719d501a4bb3db",
             "invoice":{
                "_id":"641b6d4c96719d501a4bb3d4",
                "client":{
                   "_id":"641b6d4b96719d501a4bb3d0",
                   "email":"qwe@gcc.oc",
                   "address":{
                      "country":"Palestine"
                   },
                   "fullName":"zzz vvvv"
                },
                "currency":"USD",
                "fixed":[
                   {
                      "itemName":"qqq",
                      "description":"erwqe",
                      "price":22,
                      "_id":"641b6d4c96719d501a4bb3d5"
                   }
                ],
                "freelancer":{
                   "_id":"63e104aa8bba2cb3f754d7db",
                   "firstName":"Heba",
                   "lastName":"SKHAIL"
                },
                "subTotal":22,
                "invoiceNo":"INV401",
                "status":"pending_approval"
             },
             "type":"invoice",
             "updatedAt":"2023-03-22T21:04:12.609Z"
          },
          {
             "_id":"641b6c5096719d501a4bb393",
             "invoice":{
                "_id":"641b6c4f96719d501a4bb38c",
                "client":{
                   "_id":"641b6c4f96719d501a4bb388",
                   "email":"sadsf@g,ad.com",
                   "address":{
                      "country":"Palestine"
                   },
                   "fullName":"jjjasd alkklcc"
                },
                "currency":"USD",
                "fixed":[
                   {
                      "itemName":"sdsd",
                      "description":"dfsdf",
                      "price":234234,
                      "_id":"641b6c4f96719d501a4bb38d"
                   }
                ],
                "freelancer":{
                   "_id":"63e104aa8bba2cb3f754d7db",
                   "firstName":"Heba",
                   "lastName":"SKHAIL"
                },
                "subTotal":234234,
                "invoiceNo":"INV400",
                "status":"pending_approval"
             },
             "type":"invoice",
             "updatedAt":"2023-03-22T21:00:00.149Z"
          },
          {
             "_id":"641b6b5496719d501a4bb34b",
             "invoice":{
                "_id":"641b6b5396719d501a4bb344",
                "client":{
                   "_id":"6372be62215833c0c50ba108",
                   "email":"asdas@asd.com",
                   "address":{
                      "country":"Palestine"
                   },
                   "fullName":"asdas asdasd"
                },
                "currency":"USD",
                "fixed":[
                   {
                      "itemName":"asdas",
                      "description":"asdsad",
                      "price":123111,
                      "_id":"641b6b5396719d501a4bb345"
                   }
                ],
                "freelancer":{
                   "_id":"63e104aa8bba2cb3f754d7db",
                   "firstName":"Heba",
                   "lastName":"SKHAIL"
                },
                "subTotal":123111,
                "invoiceNo":"INV399",
                "status":"pending_approval"
             },
             "type":"invoice",
             "updatedAt":"2023-03-22T20:55:48.197Z"
          },
          {
             "_id":"641b6ac396719d501a4bb309",
             "invoice":{
                "_id":"641b6ac396719d501a4bb302",
                "client":{
                   "_id":"641b6ac296719d501a4bb2fe",
                   "email":"ashjd@a.com",
                   "address":{
                      "country":"Country"
                   },
                   "fullName":"sdjkfds lksjdf"
                },
                "currency":"USD",
                "fixed":[
                   {
                      "itemName":"sdkjfsdhfq",
                      "description":"xcjvkhcxv",
                      "price":213213,
                      "_id":"641b6ac396719d501a4bb303"
                   }
                ],
                "freelancer":{
                   "_id":"63e104aa8bba2cb3f754d7db",
                   "firstName":"Heba",
                   "lastName":"SKHAIL"
                },
                "subTotal":213213,
                "invoiceNo":"INV398",
                "status":"pending_approval"
             },
             "type":"invoice",
             "updatedAt":"2023-03-22T20:53:23.505Z"
          },
          {
             "_id":"641b607d96719d501a4bb29f",
             "service":{
                "_id":"641b607d96719d501a4bb29a",
                "fixed":[
                   {
                      "itemName":"prod test job",
                      "description":"test invoice",
                      "price":110,
                      "_id":"641b607d96719d501a4bb29b"
                   },
                   {
                      "itemName":"prod test job",
                      "description":"test invoice",
                      "price":200,
                      "_id":"641b607d96719d501a4bb29c"
                   }
                ],
                "currency":"USD",
                "subTotal":310,
                "status":"pending_approval",
                "paidInvoice":0,
                "serviceNo":"LNK-124"
             },
             "type":"service",
             "updatedAt":"2023-03-22T20:09:33.448Z",
             "invoice":{
                "client":{
                   "fullName":null
                }
             }
          },
          {
             "_id":"641b5ca296719d501a4bb21e",
             "invoice":{
                "_id":"641b5ca196719d501a4bb217",
                "client":{
                   "_id":"641b5ca196719d501a4bb213",
                   "email":"mugh@gmail.com",
                   "address":{
                      "country":"Palestine"
                   },
                   "fullName":"mahmoud maug"
                },
                "currency":"USD",
                "fixed":[
                   {
                      "itemName":"asda",
                      "description":"jaszcbnjkxzcnkxkcjbzxc",
                      "price":777889,
                      "_id":"641b5ca196719d501a4bb218"
                   }
                ],
                "freelancer":{
                   "_id":"63e104aa8bba2cb3f754d7db",
                   "firstName":"Heba",
                   "lastName":"SKHAIL"
                },
                "subTotal":777889,
                "invoiceNo":"INV397",
                "status":"pending_approval"
             },
             "type":"invoice",
             "updatedAt":"2023-03-22T19:53:06.154Z"
          },
          {
             "_id":"641b5c4496719d501a4bb1de",
             "invoice":{
                "_id":"641b5c4496719d501a4bb1d7",
                "client":{
                   "_id":"641b5c4396719d501a4bb1d3",
                   "email":"qwuehw@g.com",
                   "address":{
                      "country":"Palestine"
                   },
                   "fullName":"hjashjdad akslda"
                },
                "currency":"USD",
                "fixed":[
                   {
                      "itemName":"ooooo",
                      "description":"qwegqwuyeyquwe",
                      "price":12737,
                      "_id":"641b5c4496719d501a4bb1d8"
                   }
                ],
                "freelancer":{
                   "_id":"63e104aa8bba2cb3f754d7db",
                   "firstName":"Heba",
                   "lastName":"SKHAIL"
                },
                "subTotal":12737,
                "invoiceNo":"INV396",
                "status":"pending_approval"
             },
             "type":"invoice",
             "updatedAt":"2023-03-22T19:51:32.541Z"
          }
       ]
    }
 }
